<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net471</TargetFramework>
    <Description>Several inventory organizing features.</Description>
    <Version>1.5.1</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

	<ItemGroup>
	<Reference Include="netstandard" />
    <Reference Include="0Harmony">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\dependencies\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>..\dependencies\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="spt-common">
      <HintPath>..\dependencies\spt-common.dll</HintPath>
    </Reference>
    <Reference Include="spt-reflection">
      <HintPath>..\dependencies\spt-reflection.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\dependencies\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="ItemComponent.Types">
      <HintPath>..\dependencies\ItemComponent.Types.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\dependencies\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\dependencies\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\dependencies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
        <HintPath>..\dependencies\UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\dependencies\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Serialization">
      <HintPath>..\dependencies\Sirenix.Serialization.dll</HintPath>
    </Reference>
	</ItemGroup>

</Project>
